In [2]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression

housing = fetch_california_housing()
fetch_california_housing(as_frame=True).frame.describe()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
count,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,3.870671,28.639486,5.429000,1.096675,1425.476744,3.070655,35.631861,-119.569704,2.068558
std,1.899822,12.585558,2.474173,0.473911,1132.462122,10.386050,2.135952,2.003532,1.153956
min,0.499900,1.000000,0.846154,0.333333,3.000000,0.692308,32.540000,-124.350000,0.149990
25%,2.563400,18.000000,4.440716,1.006079,787.000000,2.429741,33.930000,-121.800000,1.196000
50%,3.534800,29.000000,5.229129,1.048780,1166.000000,2.818116,34.260000,-118.490000,1.797000
75%,4.743250,37.000000,6.052381,1.099526,1725.000000,3.282261,37.710000,-118.010000,2.647250
max,15.000100,52.000000,141.909091,34.066667,35682.000000,1243.333333,41.950000,-114.310000,5.000010

In [103]:
X_housing_s = housing["data"][:, [0, 1, 2, 4, 6, 7]] #making a new matrix to only include the selected features 
y_housing = housing["target"] # y values
X_train_housing_s, X_test_housing_s, y_train_housing_s, y_test_housing_s = train_test_split(X_housing_s, y_housing, test_size = 0.3, random_state=42) #randomly splitting the data for test/training as we cannot mix them, training data is 70%
regression_line = LinearRegression().fit(X_train_housing_s, y_train_housing_s) #create a Linear Regression Model using the training data
regression_line.score(X_test_housing_s, y_test_housing_s) #testing the Linear Regression Model (LRM) using the test data
# Output = score on "how accurate" the LRM is when tested using the selected test data

0.5949702146720148

In [ ]:
# mathematically transform using log for the features that have a large range of values
from sklearn.preprocessing import FunctionTransformer
import numpy as np
X_housing_transformed = housing["data"][:, [0, 1, 2, 3, 6, 7]]

log_transformer = FunctionTransformer(np.log1p, validate=True)

X_housing_transformed[:,[2, 3]] = log_transformer.fit_transform(X_housing_transformed[:,[2, 3]]) #log transform skewed data

X_train_housing_t, X_test_housing_t, y_train_housing_t, y_test_housing_t = train_test_split(X_housing_transformed, y_housing, test_size = 0.3, random_state=42)
regression_line = LinearRegression().fit(X_train_housing_t, y_train_housing_t) #create a Linear Regression Model using the training data
regression_line.score(X_test_housing_t, y_test_housing_t) #testing the Linear Regression Model (LRM) using the test data

0.6102756376482668

In [105]:
# If we use all of the given features from the initial data,
X_train_housing_all, X_test_housing_all, y_train_housing_all, y_test_housing_all = train_test_split(housing["data"], y_housing, test_size = 0.3, random_state=42)
regression_line = LinearRegression().fit(X_train_housing_all, y_train_housing_all)
regression_line.score(X_test_housing_all, y_test_housing_all)

0.595770232606166

Logistic regression using wine data

In [73]:
from sklearn.datasets import load_wine
from sklearn.linear_model import LogisticRegression
wine = load_wine(as_frame=True).frame # this loads all the data entries
wine.describe()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
count,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000
mean,13.000618,2.336348,2.366517,19.494944,99.741573,2.295112,2.029270,0.361854,1.590899,5.058090,0.957449,2.611685,746.893258,0.938202
std,0.811827,1.117146,0.274344,3.339564,14.282484,0.625851,0.998859,0.124453,0.572359,2.318286,0.228572,0.709990,314.907474,0.775035
min,11.030000,0.740000,1.360000,10.600000,70.000000,0.980000,0.340000,0.130000,0.410000,1.280000,0.480000,1.270000,278.000000,0.000000
25%,12.362500,1.602500,2.210000,17.200000,88.000000,1.742500,1.205000,0.270000,1.250000,3.220000,0.782500,1.937500,500.500000,0.000000
50%,13.050000,1.865000,2.360000,19.500000,98.000000,2.355000,2.135000,0.340000,1.555000,4.690000,0.965000,2.780000,673.500000,1.000000
75%,13.677500,3.082500,2.557500,21.500000,107.000000,2.800000,2.875000,0.437500,1.950000,6.200000,1.120000,3.170000,985.000000,2.000000
max,14.830000,5.800000,3.230000,30.000000,162.000000,3.880000,5.080000,0.660000,3.580000,13.000000,1.710000,4.000000,1680.000000,2.000000

In [109]:
wine_data = load_wine()
wine_data
X_wine = wine_data["data"][:, [0, 1, 5, 6, 9, 10, 11, 12]]
y_wine = wine_data["target"]

X_train_wine_s, X_test_wine_s, y_train_wine_s, y_test_wine_s = train_test_split(X_wine, y_wine, test_size = 0.3, random_state=42)
log_reg = LogisticRegression(random_state=67, max_iter=5000).fit(X_train_wine_s, y_train_wine_s,)
log_reg.score(X_train_wine_s, y_train_wine_s)

0.967741935483871

In [112]:
X_wine_transformed = wine_data["data"][:, [0, 1, 5, 6, 9, 10, 11, 12]]

log_transformer = FunctionTransformer(np.log1p, validate=True)

X_wine_transformed[:,[4, 7]] = log_transformer.fit_transform(X_wine_transformed[:,[4, 7]])
X_wine_transformed

X_train_wine_t, X_test_wine_t, y_train_wine_t, y_test_wine_t = train_test_split(X_wine_transformed, y_wine, test_size = 0.3, random_state=21)
log_reg_t = LogisticRegression(random_state=67, max_iter = 5000).fit(X_train_wine_t, y_train_wine_t) #create a Logistic Regression Model using the training data
log_reg_t.score(X_test_wine_t, y_test_wine_t) #testing the Linear Regression Model (LRM) using the test data

0.9814814814814815

In [111]:
X_wine_all = wine_data["data"]
X_train_wine_all, X_test_wine_all, y_train_wine_all, y_test_wine_all = train_test_split(X_wine_all, y_wine, test_size = 0.3, random_state=21)
log_reg_all = LogisticRegression(random_state=67, max_iter=5500).fit(X_train_wine_all, y_train_wine_all)
log_reg_all.score(X_test_wine_all, y_test_wine_all)

0.9814814814814815