In [ ]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression

housing = fetch_california_housing()
housing #loads the data as arrays

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]], shape=(20640, 8)),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894], shape=(20640,)),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 20640\n\n:Number of Attributes: 8 numeric, predictive attributes and the target\n\n:Attribute Information:\n    - MedInc        median income in block group\n    - HouseAge      median house age in block group\n    - AveRooms      average number of rooms per household\n    - AveBedrms     average number of bedrooms per household\n    - Population    block group population\n    - AveOccup      average number of household members\n    - Latitude      block group latitude\n    - Longitude     block group longitude\n\n:Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib:\nhttps://lib.stat.cmu.edu/datasets/houses.zip\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. rubric:: References\n\n- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n  Statistics and Probability Letters, 33:291-297, 1997.\n'}

In [ ]:
fetch_california_housing(as_frame=True).frame.describe() # just to see statistics of the data

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
count,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,3.870671,28.639486,5.429000,1.096675,1425.476744,3.070655,35.631861,-119.569704,2.068558
std,1.899822,12.585558,2.474173,0.473911,1132.462122,10.386050,2.135952,2.003532,1.153956
min,0.499900,1.000000,0.846154,0.333333,3.000000,0.692308,32.540000,-124.350000,0.149990
25%,2.563400,18.000000,4.440716,1.006079,787.000000,2.429741,33.930000,-121.800000,1.196000
50%,3.534800,29.000000,5.229129,1.048780,1166.000000,2.818116,34.260000,-118.490000,1.797000
75%,4.743250,37.000000,6.052381,1.099526,1725.000000,3.282261,37.710000,-118.010000,2.647250
max,15.000100,52.000000,141.909091,34.066667,35682.000000,1243.333333,41.950000,-114.310000,5.000010

Relevant Features IN MY OPINIONNN?: MedInc, HouseAge (?), AveRooms, Population, Latitude, Longitude
I am unsure of the HouseAge so we can discuss abt that

In [ ]:
X = housing["data"][:, [0, 1, 2, 4, 6, 7]] #making a new matrix to only include the selected features 
y = housing["target"] # y values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=676767) #randomly splitting the data for test/training as we cannot mix them, training data is 70%
regression_line = LinearRegression().fit(X_train, y_train) #create a Linear Regression Model using the training data
regression_line.score(X_test, y_test) #testing the Linear Regression Model (LRM) using the test data
# Output = score on "how accurate" the LRM is when tested using the selected test data

0.5937165442433183

In [ ]:
# mathematically transform = log?? to remove the outliers?? (because as we see in the statistics, AveRooms and Population have massive outliers)
from sklearn.preprocessing import FunctionTransformer
import numpy as np
X_copy = housing["data"][:, [0, 1, 2, 4, 6, 7]]

# Initialize FunctionTransformer with np.log1p
# validate=True ensures the input is finite, feature_names_out='original' for column names
log_transformer = FunctionTransformer(np.log1p, validate=True)

X_copy[:,[2, 3]] = log_transformer.fit_transform(X_copy[:,[2,3]])
X_copy #new transformed dataset

array([[   8.3252    ,   41.        ,    2.07745544,    5.77765232,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    1.97936386,    7.784057  ,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    2.22873784,    6.20859003,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    1.82544288,    6.91572345,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    1.84522328,    6.60934924,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    1.8333359 ,    7.23561914,
          39.37      , -121.24      ]], shape=(20640, 6))

In [ ]:
# If we use all of the given features from the initial data,
X_train_m, X_test_m, y_train_m, y_test_m = train_test_split(X_copy, y, test_size = 0.3, random_state=21)
regression_line = LinearRegression().fit(X_train_m, y_train_m)
regression_line.score(X_test_m, y_test_m)
# Output: slightly higher score LOL

0.5915605076846

In [ ]:
# Part 2: logistic regression for the wine data
from sklearn.datasets import load_wine
from sklearn.linear_model import LogisticRegression
wine = load_wine(as_frame=True).frame # so the data looks nice
wine.describe() # statistics

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
count,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000
mean,13.000618,2.336348,2.366517,19.494944,99.741573,2.295112,2.029270,0.361854,1.590899,5.058090,0.957449,2.611685,746.893258,0.938202
std,0.811827,1.117146,0.274344,3.339564,14.282484,0.625851,0.998859,0.124453,0.572359,2.318286,0.228572,0.709990,314.907474,0.775035
min,11.030000,0.740000,1.360000,10.600000,70.000000,0.980000,0.340000,0.130000,0.410000,1.280000,0.480000,1.270000,278.000000,0.000000
25%,12.362500,1.602500,2.210000,17.200000,88.000000,1.742500,1.205000,0.270000,1.250000,3.220000,0.782500,1.937500,500.500000,0.000000
50%,13.050000,1.865000,2.360000,19.500000,98.000000,2.355000,2.135000,0.340000,1.555000,4.690000,0.965000,2.780000,673.500000,1.000000
75%,13.677500,3.082500,2.557500,21.500000,107.000000,2.800000,2.875000,0.437500,1.950000,6.200000,1.120000,3.170000,985.000000,2.000000
max,14.830000,5.800000,3.230000,30.000000,162.000000,3.880000,5.080000,0.660000,3.580000,13.000000,1.710000,4.000000,1680.000000,2.000000

In [ ]:
wine

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0,2
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0,2
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0,2
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0,2
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0,2

Features I THINK? (with index): alcalinity (3), phenols (5), flavanoids (6), nonflavanoid_phenols (7), hue (10), od280/od315 (11),

In [ ]:
wine_data = load_wine()
wine_data
Xw = wine_data["data"][:, [3, 5, 6, 7, 10, 11, 12]]
yw = wine_data["target"]
X_train_w, X_test_w, y_train_w, y_test_w = train_test_split(Xw, yw, test_size = 0.3, random_state=21)
log_reg = LogisticRegression(random_state=67, max_iter=1000).fit(X_train_w, y_train_w,)
log_reg.score(X_train_w, y_train_w)
# from sklearn.feature_selection import VarianceThreshold
# sel = VarianceThreshold(threshold=(.8 * (1 - .8)))
# sel.fit_transform(Xw)[0]

In [ ]:
Xw_all = wine_data["data"]
X_train_wall, X_test_wall, y_train_wall, y_test_wall = train_test_split(Xw_all, yw, test_size = 0.3, random_state=21)
log_reg_all = LogisticRegression(random_state=67, max_iter=1000).fit(X_train_wall, y_train_wall)
log_reg_all.score(X_test_wall, y_test_wall)